flask/flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class PostForm(FlaskForm):
    """docstring for PostForm."""

    title = StringField(
        'Título',
        validators=[
            DataRequired()
        ]
    )

    description = StringField('Descrição')

    content = TextAreaField(
        'Conteudo',
        validators=[
            DataRequired()
        ]
    )

    tags = StringField('tags')

    submit = SubmitField('Post')


class CommentForm(FlaskForm):
    """docstring for CommentForm."""

    content = TextAreaField(
        'Novo comentário',
        validators=[
            DataRequired(),
            Length(max=200)
        ]
    )

    submit = SubmitField('Comentar')

flask/flaskblog/main/routes.py
from flaskblog.models import Post
from flask import (
    render_template,
    request,
    Blueprint,
    redirect,
    url_for
)

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(
        Post.date_posted.desc()
    ).paginate(
        per_page=6,
        page=page
    )

    return render_template('home.html', posts=posts)


@main.route('/about')
def about():
    return render_template('about.html', title='Sobre')


@main.route('/search/<string:tags>', methods=['GET', 'POST'])
def search(tags=None):
    if not tags:
        return redirect(url_for('main.home'))
    page = request.args.get('page', 1, type=int)
    post_list = [
        post.id for post in Post.query.all()
        if tags in post.tags
    ]

    posts = Post.query\
        .filter(
            Post.id.in_(post_list)
        )\
        .order_by(
            Post.date_posted.desc()
        )\
        .paginate(
            per_page=6,
            page=page
        )

    return render_template(
        'search.html',
        title='Search',
        tags=tags,
        posts=posts
    )

flask/flaskblog/posts/routes.py
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post, Comment
from flaskblog.posts.forms import PostForm, CommentForm
from flaskblog.main.forms import SearchForm
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    g,
    request,
    abort,
    Blueprint
)

posts = Blueprint('posts', __name__)


@posts.before_app_request
def before_request():
    g.search_form = SearchForm()

    if g.search_form.validate_on_submit():
        return redirect(
            url_for('main.search', tags=g.search_form.search_term.data.lower())
        )


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(
            title=form.title.data,
            description=form.description.data,
            content=form.content.data,
            tags=form.tags.data.lower(),
            author=current_user
        )

        db.session.add(post)
        db.session.commit()

        flash('Post criado!', 'success')
        return redirect(url_for('main.home'))

    return render_template(
        'create_post.html',
        title='Novo Post',
        form=form,
        legend='Novo post'
    )


@posts.route('/post/<int:post_id>', methods=['GET', 'POST'])
def post(post_id):
    page = request.args.get('page', 1, type=int)
    post = Post.query.get_or_404(post_id)
    comments = Comment.query\
        .filter_by(
            post=post
        )\
        .order_by(
            Comment.date_posted.desc()
        )\
        .paginate(
            per_page=6,
            page=page
        )
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment(
            content=form.content.data,
            post_id=post.id,
            user_id=current_user.id
        )
        db.session.add(new_comment)
        db.session.commit()

        flash('Comentário adicionado', 'success')
        return redirect(url_for('posts.post', post_id=post_id))

    return render_template(
        'post.html',
        title=post.title,
        post=post,
        form=form,
        comments=comments
    )


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.description = form.description.data
        post.tags = form.tags.data.lower()
        db.session.commit()
        flash("O post foi atualizado", 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.description.data = post.description
        form.tags.data = post.tags

    return render_template(
        'create_post.html',
        title='Editar post',
        form=form,
        legend='Editar post'
    )


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post=post).all()
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    for comment in comments:
        db.session.delete(Comment.query.get(comment.id))

    db.session.commit()

    flash('Post deletado', 'success')
    return redirect(url_for('main.home'))


@posts.route('/comment/<int:comment_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    post_id = comment.post_id

    if comment.author != current_user:
        abort(403)

    db.session.delete(comment)
    db.session.commit()

    flash('Comment deleted', 'success')
    return redirect(url_for('posts.post', post_id=post_id))

flask/flaskblog/users/routes.py
from flask import (
    render_template,
    url_for,
    flash,
    redirect,
    request,
    Blueprint,
    abort
)
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.models import User, Post, Comment
from flaskblog.users.utils import (
    save_image,
    send_reset_email,
    send_delete_email
)
from flaskblog.users.forms import (
    RegistrationForm,
    LoginForm,
    UpdateAccountForm,
    RequestResetForm,
    RequestPasswordForm
)


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():

        hashed_password = bcrypt.generate_password_hash(
            form.password.data
        ).decode('utf-8')

        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password
        )

        db.session.add(user)
        db.session.commit()

        flash(
            f"""
                Conta criada com sucesso!\n
                Bem-vindo {form.username.data} ao meu blog!
            """,
            'success'
        )
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Registrar', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user and bcrypt.check_password_hash(
            user.password,
            form.password.data
        ):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash('Login com sucesso', 'success')
            return redirect(
                next_page
            ) if next_page else redirect(url_for('main.home'))
        else:
            flash('Credenciais incorretas', 'danger')

    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_image(form.picture.data)
            current_user.image_file = picture_file

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('As informações da conta foram atualizadas', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for(
        'static',
        filename=f'profile_pics/{current_user.image_file}'
    )
    return render_template(
        'account.html',
        title='Minha conta',
        image_file=image_file,
        form=form
    )


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query\
        .filter_by(
            author=user
        )\
        .order_by(
            Post.date_posted.desc()
        )\
        .paginate(
            per_page=6,
            page=page
        )

    return render_template('user_post.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('E-mail enviado. Confira sua caixa de entrada', 'info')
        return redirect(url_for('users.login'))

    return render_template(
        'reset_request.html',
        title='Recuperar senha',
        form=form
    )


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def request_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)

    if user is None:
        flash('Esse token foi expirado ou é inválido.', 'warning')
        return redirect(url_for('users.reset_request'))

    form = RequestPasswordForm()
    if form.validate_on_submit():

        hashed_password = bcrypt.generate_password_hash(
            form.password.data
        ).decode('utf-8')

        user.password = hashed_password
        db.session.commit()

        flash("Sua senha foi alterada com sucesso!", 'success')
        return redirect(url_for('users.login'))

    return render_template(
        'reset_token.html',
        title='Recuperar senha',
        form=form
    )


@users.route('/user/<int:user_id>/delete_user', methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
    user = User.query.filter_by(id=user_id).first()
    if user != current_user:
        abort(403)

    send_delete_email(user)
    flash('Um E-mail de confirmação foi enviado.', 'info')
    return redirect(url_for('users.logout'))


@users.route(
    '/user/<int:user_id>/delete_user/<token>',
    methods=['GET', 'POST']
)
def request_token_delete(user_id, token):
    user_token = User.verify_reset_token(token)

    if user_token is None:
        flash('Esse token foi expirado ou é inválido.', 'warning')
        return redirect(url_for('main.home'))

    user = User.query.get_or_404(user_id)

    comments = Comment.query.filter_by(user_id=user.id).all()
    for comment in comments:
        db.session.delete(comment)

    posts = Post.query.filter_by(author=user).all()
    for post in posts:
        db.session.delete(post)

    db.session.delete(user)
    db.session.commit()

    flash('Conta deletada', 'success')
    return redirect(url_for('main.home'))

flask/flaskblog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
<h1>About page</h1>
{% endblock content %}

flask/flaskblog/templates/account.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <div class="content-section">
        <form action="" method="POST" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Informações da conta</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}

                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span><br />
                    {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <button type="button" class="btn btn-outline-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Deletar conta</button>
            </div>
        </form>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Deletar conta?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <form action="{{ url_for('users.delete_user', user_id=current_user.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Deletar">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flask/flaskblog/templates/create_post.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                {{ form.title(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.description.label(class="form-control-label") }}
                {% if form.description.errors %}
                {{ form.description(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.description.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.description(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.tags.label(class="form-control-label") }}
                {% if form.tags.errors %}
                {{ form.tags(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.tags.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.tags(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

flask/flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% if title %}
    <title>Flask blog - {{ title }}</title>
    {% else %}
    <title>Flask blog</title>
    {% endif %}
</head>

<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{{ url_for('main.home') }}">Flask Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('main.about') }}">Sobre</a>
                        {% if g.search_form %}

                        <form class="form-inline ml-3" action="" method="POST">
                            {{ g.search_form.hidden_tag() }}
                            <div class="input-group input-group-sm">
                                {{ g.search_form.search_term(class="form-control") }}
                                <div class="input-group-append">
                                    {{ g.search_form.submit(class="input-group-text", id="basic-addon1 inputGroup-sizing-sm") }}
                                </div>
                            </div>
                        </form>
                        {% endif %}

                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">Novo Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Conta</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Registrar</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Links</h3>
                    <p class='text-muted'>Alguns links uteis:
                    <ul class="list-group">
                        <li class="list-group-item list-group-item-light"><a href="{{ url_for('users.user_posts', username='Caio Vieira') }}">Posts do adm</a></li>
                        <li class="list-group-item list-group-item-light"><a href="{{ url_for('main.about') }}">Sobre</a></li>
                    </ul>
                    </p>
                </div>
            </div>
        </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>

</html>

flask/flaskblog/templates/layouts.html
{% macro post_container(post, current_user=False, show_content=False) %}
<article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" alt="" />
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
            <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if show_content and post.author == current_user%}
            <div class="">
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Editar</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Apagar</button>
            </div>
            {% endif %}
        </div>
        {% if show_content %}
        <h2 class="article-title">{{ post.title }}</h2>
        {% else %}
        <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
        {% endif %}
        <small class="article-content">{{ post.description }}</small>
        {% if show_content %}
        <p class="article-content">{{ post.content }}</p>
        {% endif %}
        {% if post.tags %}
        <small>tags:</small>
        <br>
        <div class="btn-group" role="group">
            {% for tag in post.tags.split(' ') %}
            <form action="{{ url_for('main.search', tags=tag) }}" class="ml-1 mr-1">
                <button type="submit" class="btn btn-secondary btn-sm">{{ tag.lower() }}</button>
            </form>
            {% endfor %}
        </div>
        {% endif %}
    </div>
</article>
{% endmacro %}

flask/flaskblog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember(class='form-check-input') }}
                {{ form.remember.label(class='form-check-label') }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Esqueci minha senha</a>
            </small>
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Não tem conta? <a class="ml-2" href="{{ url_for('users.register') }}">Criar conta</a>
    </small>
</div>
{% endblock content %}

flask/flaskblog/templates/post.html
{% from 'layouts.html' import post_container %}
{% extends 'layout.html' %}
{% block content %}
{{ post_container(post=post, current_user=current_user, show_content=True) }}
<!--Comments-->
<h5>Comentários</h5>
{% if current_user.is_authenticated %}
<div class="content-section">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                {{ form.content(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group ">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endif %}
{% for comment in comments.items %}
<article class="media content-section">
    <img class="rounded-circle comment-img" src="{{ url_for('static', filename='profile_pics/' + comment.author.image_file) }}" alt="" />
    <div class="media-body">
        <div class="article-metadata">
            <a class="mr-2" href="{{ url_for('users.user_posts', username=comment.author.username) }}">{{ comment.author.username }}</a>
            <small class="text-muted">{{ comment.date_posted.strftime('%Y-%m-%d') }}</small>
            {% if comment.author == current_user %}
            <small><a class="float-right" href="{{ url_for('posts.delete_comment', comment_id=comment.id) }}">delete</a></small>
            {% endif %}
        </div>
        <p class="article-content">{{ comment.content }}</p>
    </div>
</article>
{% endfor %}
{% for page_num in comments.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if comments.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('posts.post', page=page_num, post_id=post.id) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('posts.post', page=page_num, post_id=post.id) }}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
<!-- Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Deletar post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Deletar">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flask/flaskblog/templates/search.html
{% extends 'home.html' %}
{% block title %}
<h1 class="mb-3">Search results for '{{ tags }}' ({{ posts.total }})</h1>
{% endblock title %}

flask/flaskblog/templates/user_post.html
{% extends 'home.html' %}
{% block title %}
<h1 class="mb-3">Posts de {{ user.username }} ({{ posts.total }})</h1>
{% endblock title %}